# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    listenAddress: "0.0.0.0" # Maps frontend service to host port 80
    protocol: tcp
  - containerPort: 30081
    hostPort: 3001
    listenAddress: "0.0.0.0" # Maps backend service to host port 3001
    protocol: tcp
